### ISSUE TITLE
Add MIT license

### ISSUE THREAD

**Issue by skunkworker** [jobapis/collector#1]
Hi I like this project a lot, but as of right now there is no license for the software. I am a fan of the MIT license for open source projects. What do you think?

**Comment by karllhughes** [comment]
Good call, that was an oversight on my part. All the other packages specifically mention the Apache 2.0 license on our site: https://www.jobapis.com/license/

If you want to add something to the Readme specifically mentioning this license, feel free to make a PR. Thanks!

**Comment by karllhughes** [comment]
Done: https://github.com/jobapis/collector#legal
