### ISSUE TITLE
ERROR: no matching manifest for linux/arm

### ISSUE THREAD

**Issue by felixchang** [jobapis/collector#2]
Hello,

I am running this is on Raspberry Pi. Run the command npm run -s composer:install.

This is what I get:

Unable to find image 'composer:latest' locally
latest: Pulling from library/composer
docker: no matching manifest for linux/arm in the manifest list entries.
See 'docker run --help'.

Docker verison:

Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:24:08 2018
 OS/Arch:       linux/arm
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:20:13 2018
  OS/Arch:      linux/arm
  Experimental: false

Docker info:

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.59-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 923.4MiB
Name: RP3
ID: X6QD:H4JL:GW4H:R6L6:DL2Z:N36J:J2ER:DZ5K:H2LK:UVBO:Y7XH:WEK7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

Thanks for the help.

**Comment by karllhughes** [comment]
This is an issue with Docker for Raspberry Pi, and it looks like others have run into it as well:

https://github.com/moby/moby/issues/34875
https://github.com/docker/distribution/issues/2405

So I'm going to close this issue as the problem doesn't seem to stem from this project, but rather with Docker itself, so I can't really do anything to fix it. Good luck!
